# sudo: false

language: python

python:
#  - '3.5'
#  - '3.6'
  - '3.7'

env:
  - ENV_STRING=master
#  - ENV_STRING=pandas0.24.1
#  - ENV_STRING=pandas0.24.0
#
#  - ENV_STRING=pandas0.23.4
#  - ENV_STRING=pandas0.23.3
#  - ENV_STRING=pandas0.23.2
#  - ENV_STRING=pandas0.23.1
#  - ENV_STRING=pandas0.23.0
#
#  - ENV_STRING=pandas0.22.0
#
#  - ENV_STRING=pandas0.21.1
#  - ENV_STRING=pandas0.21.0
#
#  - ENV_STRING=pandas0.20.3
#  - ENV_STRING=pandas0.20.2
#  - ENV_STRING=pandas0.20.1
#  - ENV_STRING=pandas0.20.0
#
#  - ENV_STRING=pandas0.19.2
#  - ENV_STRING=pandas0.19.1
#  - ENV_STRING=pandas0.19.0
#
#  - ENV_STRING=pyspark2.4.0
#  - ENV_STRING=pyspark2.3.1

#  - ENV_STRING=dask1.1.5


# Remove python/pandas version interactions which do not have wheels on pypi
matrix:
  exclude:
    - python: '3.7'
      env: ENV_STRING=pandas0.22.0
    - python: '3.7'
      env: ENV_STRING=pandas0.21.1
    - python: '3.7'
      env: ENV_STRING=pandas0.21.0
    - python: '3.7'
      env: ENV_STRING=pandas0.20.3
    - python: '3.7'
      env: ENV_STRING=pandas0.20.2
    - python: '3.7'
      env: ENV_STRING=pandas0.20.1
    - python: '3.7'
      env: ENV_STRING=pandas0.20.0
    - python: '3.7'
      env: ENV_STRING=pandas0.19.2
    - python: '3.7'
      env: ENV_STRING=pandas0.19.1
    - python: '3.7'
      env: ENV_STRING=pandas0.19.0
    - python: '3.6'
      env: ENV_STRING=pandas0.19.0

dist: xenial

before_install:
  - source travisci/java_install.sh

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade setuptools
  - travis_retry pip install codecov flake8 tox

script:
  - source travisci/tox_invocation.sh

after_success:
  - source travisci/coveralls_master.sh

cache: pip
